# Generated by Django 5.2.17 on 2026-10-01 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp (null = active, not null = deleted)', null=True, verbose_name='Deleted At')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount — DecimalField (never FloatField)', max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(db_index=True, default='USD', max_length=3, verbose_name='Currency')),
                ('payment_date', models.DateField(db_index=True, verbose_name='Payment Date')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Reference Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund')], db_index=True, default='completed', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='reservations.reservation', verbose_name='Reservation')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='unique_payment_method_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hotel', 'payment_date'], name='idx_payment_hotel_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hotel', 'currency', 'payment_date'], name='idx_payment_curr_date'),
        ),
    ]
