# Generated by Django 5.2.17 on 2026-10-01 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="ISO 639-1 code (e.g., 'en', 'ar', 'fr')", max_length=10, unique=True, verbose_name='Language Code')),
                ('name', models.CharField(help_text='English name of the language', max_length=100, verbose_name='Language Name')),
                ('native_name', models.CharField(blank=True, help_text='Name in the language itself (e.g., العربية)', max_length=100, verbose_name='Native Name')),
                ('is_rtl', models.BooleanField(default=False, help_text='Right-to-left language direction?', verbose_name='Is RTL')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('code', models.CharField(help_text='Short code (e.g., STD, DLX, STE)', max_length=20, verbose_name='Room Type Code')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Default nightly rate (DecimalField — never FloatField for money)', max_digits=10, verbose_name='Base Price per Night')),
                ('max_occupancy', models.PositiveSmallIntegerField(default=2, verbose_name='Max Occupancy')),
                ('amenities', models.JSONField(blank=True, default=list, help_text="List of amenity strings (e.g., ['WiFi', 'AC', 'Mini-bar'])", verbose_name='Amenities')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Sort Order')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('room_number', models.CharField(help_text="Unique within the hotel (e.g., '101', '201A')", max_length=20, verbose_name='Room Number')),
                ('floor', models.SmallIntegerField(default=1, verbose_name='Floor')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('cleaning', 'Being Cleaned'), ('inspecting', 'Being Inspected'), ('out_of_order', 'Out of Order')], db_index=True, default='available', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this room', verbose_name='Notes')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype', verbose_name='Room Type')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room type name in this language', max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_translations', to='rooms.language', verbose_name='Language')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='rooms.roomtype', verbose_name='Room Type')),
            ],
            options={
                'verbose_name': 'Room Type Translation',
                'verbose_name_plural': 'Room Type Translations',
            },
        ),
        migrations.CreateModel(
            name='BookingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('name', models.CharField(help_text='e.g., Walk-in, Booking.com, Phone', max_length=100, verbose_name='Source Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_online', models.BooleanField(default=False, help_text='Online travel agency (OTA) or direct booking?', verbose_name='Is Online')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage (if applicable)', max_digits=5, verbose_name='Commission Rate (%)')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Booking Source',
                'verbose_name_plural': 'Booking Sources',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('hotel', 'name'), name='unique_booking_source_per_hotel')],
            },
        ),
        migrations.CreateModel(
            name='HotelLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, help_text='Default language for this hotel', verbose_name='Is Default')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_languages', to='rooms.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Hotel Language',
                'verbose_name_plural': 'Hotel Languages',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('hotel', 'language'), name='unique_hotel_language')],
            },
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='unique_room_type_code_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'status'], name='idx_room_hotel_status'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'room_type', 'status'], name='idx_room_hotel_type_status'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'room_number'), name='unique_room_number_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='roomtypetranslation',
            constraint=models.UniqueConstraint(fields=('room_type', 'language'), name='unique_room_type_translation'),
        ),
    ]
