# Generated by Django 5.2.17 on 2026-10-01 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('payments', '0001_initial'),
        ('reservations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='payments.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='payments.payment', verbose_name='Related Payment'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='reservations.reservation', verbose_name='Related Reservation'),
        ),
        migrations.AddField(
            model_name='monthlyclosing',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_closings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyclosing',
            name='hotel',
            field=models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel'),
        ),
        migrations.AddConstraint(
            model_name='dailyclosing',
            constraint=models.UniqueConstraint(fields=('hotel', 'business_date'), name='unique_daily_closing_per_hotel_date'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('hotel', 'from_currency', 'to_currency', 'effective_date'), name='unique_exchange_rate_per_hotel_date'),
        ),
        migrations.AddConstraint(
            model_name='financecategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'name', 'type'), name='unique_finance_category_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['hotel', 'transaction_date'], name='idx_ftx_hotel_date'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['hotel', 'currency', 'transaction_date'], name='idx_ftx_hotel_currency_date'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['hotel', 'type', 'transaction_date'], name='idx_ftx_hotel_type_date'),
        ),
        migrations.AddConstraint(
            model_name='monthlyclosing',
            constraint=models.UniqueConstraint(fields=('hotel', 'year', 'month'), name='unique_monthly_closing_per_hotel'),
        ),
    ]
