# Generated by Django 5.2.17 on 2026-09-28 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('name', models.CharField(help_text='Full name of the hotel', max_length=255, verbose_name='Hotel Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated from name)', max_length=100, unique=True, verbose_name='Slug')),
                ('subdomain', models.CharField(db_index=True, help_text="Subdomain for tenant routing (e.g., 'hilton' → hilton.saas.com)", max_length=100, unique=True, verbose_name='Subdomain')),
                ('email', models.EmailField(help_text='Official hotel contact email', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Hotel phone number', max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, help_text='Full postal address', verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (e.g., EG, US)', max_length=2, verbose_name='Country')),
                ('timezone', models.CharField(default='UTC', help_text='Hotel local timezone (e.g., Africa/Cairo)', max_length=50, verbose_name='Timezone')),
                ('default_currency', models.CharField(default='USD', help_text='ISO 4217 currency code (e.g., USD, EGP)', max_length=3, verbose_name='Default Currency')),
                ('default_language', models.CharField(default='en', help_text='ISO 639-1 language code (e.g., en, ar)', max_length=10, verbose_name='Default Language')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('trial', 'Trial')], db_index=True, default='trial', help_text='Current hotel status (active/inactive/suspended/trial)', max_length=20, verbose_name='Status')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotels/logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'is_active'], name='idx_hotel_status_active')],
            },
        ),
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('checkin_time', models.TimeField(default='14:00', help_text='Default check-in time (e.g., 14:00)', verbose_name='Check-in Time')),
                ('checkout_time', models.TimeField(default='12:00', help_text='Default check-out time (e.g., 12:00)', verbose_name='Check-out Time')),
                ('exchange_rate_mode', models.CharField(choices=[('manual', 'Manual (staff updates rates)'), ('auto', 'Auto (fetch from API)'), ('fixed', 'Fixed (no conversion)')], default='manual', max_length=10, verbose_name='Exchange Rate Mode')),
                ('allow_overbooking', models.BooleanField(default=False, help_text='Allow booking a room that might be occupied', verbose_name='Allow Overbooking')),
                ('max_advance_booking_days', models.PositiveIntegerField(default=365, help_text='Maximum days in advance a reservation can be made', verbose_name='Max Advance Booking Days')),
                ('auto_close_daily', models.BooleanField(default=True, help_text='Automatically close the daily financial period at midnight', verbose_name='Auto Close Daily')),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers (e.g., INV → INV-0001)', max_length=10, verbose_name='Invoice Prefix')),
                ('hotel', models.OneToOneField(help_text='The hotel these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel Settings',
                'verbose_name_plural': 'Hotel Settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
