# Generated by Django 5.2.17 on 2026-10-01 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('rooms', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('check_in', models.DateField(db_index=True, verbose_name='Check-in Date')),
                ('check_out', models.DateField(db_index=True, verbose_name='Check-out Date')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='Adults')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Children')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Price snapshot at booking time — DecimalField (never Float)', max_digits=12, verbose_name='Total Price')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Checked In At')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Checked Out At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation Reason')),
                ('booking_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='rooms.bookingsource', verbose_name='Booking Source')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer', verbose_name='Customer')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp (null = active, not null = deleted)', null=True, verbose_name='Deleted At')),
                ('check_in', models.DateField(verbose_name='Check-in Date')),
                ('check_out', models.DateField(verbose_name='Check-out Date')),
                ('nightly_price', models.DecimalField(decimal_places=2, help_text='Price per night at booking time — immutable snapshot', max_digits=10, verbose_name='Nightly Price (snapshot)')),
                ('nights', models.PositiveSmallIntegerField(verbose_name='Nights')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='Adults')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Children')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_rooms', to='reservations.reservation', verbose_name='Reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='rooms.room', verbose_name='Room')),
                ('room_type', models.ForeignKey(help_text='Snapshot of room type at booking time', on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='rooms.roomtype', verbose_name='Room Type (snapshot)')),
            ],
            options={
                'verbose_name': 'Reservation Room',
                'verbose_name_plural': 'Reservation Rooms',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationRoomChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Old Nightly Price')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New Nightly Price')),
                ('price_difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Difference')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('new_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_reservation_changes', to='rooms.room', verbose_name='New Room')),
                ('old_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_reservation_changes', to='rooms.room', verbose_name='Old Room')),
                ('reservation_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='reservations.reservationroom', verbose_name='Reservation Room')),
            ],
            options={
                'verbose_name': 'Reservation Room Change',
                'verbose_name_plural': 'Reservation Room Changes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['hotel', 'status'], name='idx_reservation_hotel_status'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['hotel', 'check_in', 'check_out'], name='idx_reservation_hotel_dates'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['hotel', 'customer'], name='idx_reservation_hotel_customer'),
        ),
        migrations.AddIndex(
            model_name='reservationroom',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='idx_resroom_room_dates'),
        ),
        migrations.AddIndex(
            model_name='reservationroom',
            index=models.Index(fields=['reservation'], name='idx_resroom_reservation'),
        ),
    ]
