# Generated by Django 5.2.17 on 2026-10-01 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Phone')),
                ('nationality', models.CharField(blank=True, help_text='Country name or ISO 3166-1 alpha-2 code', max_length=100, verbose_name='Nationality')),
                ('id_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driving_license', 'Driving License'), ('other', 'Other')], max_length=30, verbose_name='ID Type')),
                ('id_number', models.CharField(blank=True, max_length=100, verbose_name='ID Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('vip_status', models.BooleanField(db_index=True, default=False, verbose_name='VIP Status')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this guest', verbose_name='Notes')),
                ('total_stays', models.PositiveIntegerField(default=0, verbose_name='Total Stays')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['hotel', 'phone'], name='idx_customer_hotel_phone'), models.Index(fields=['hotel', 'email'], name='idx_customer_hotel_email'), models.Index(fields=['hotel', 'last_name'], name='idx_customer_hotel_name')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('employee_id', models.CharField(blank=True, help_text='Internal employee number (unique per hotel)', max_length=50, verbose_name='Employee ID')),
                ('position', models.CharField(blank=True, help_text='Job title (e.g., Receptionist, Housekeeper)', max_length=100, verbose_name='Position')),
                ('department', models.CharField(choices=[('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('food_beverage', 'Food & Beverage'), ('management', 'Management'), ('security', 'Security'), ('other', 'Other')], db_index=True, default='front_desk', max_length=30, verbose_name='Department')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['hotel', 'department'], name='idx_employee_hotel_department')],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'user'), name='unique_employee_per_hotel')],
            },
        ),
    ]
