# Generated by Django 5.2.17 on 2026-10-01 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('reservations', '0001_initial'),
        ('rooms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCleaning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('inspected', 'Inspected')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='Inspected At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='customers.employee', verbose_name='Assigned To')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='reservations.reservation', verbose_name='Related Reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Cleaning',
                'verbose_name_plural': 'Room Cleanings',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['hotel', 'status'], name='idx_cleaning_hotel_status'), models.Index(fields=['room', 'status'], name='idx_cleaning_room_status')],
            },
        ),
    ]
