# Generated by Django 5.2.17 on 2026-10-01 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('rooms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique identifier (auto-generated)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (auto-set)', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp (auto-updated)', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active (soft-filter, not delete)', verbose_name='Is Active')),
                ('title', models.CharField(max_length=200, verbose_name='Issue Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10, verbose_name='Priority')),
                ('blocking', models.BooleanField(db_index=True, default=False, help_text='If True, room cannot become AVAILABLE until this issue is resolved.', verbose_name='Blocking')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='customers.employee', verbose_name='Assigned To')),
                ('hotel', models.ForeignKey(help_text='The hotel this record belongs to (multi-tenancy scope)', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.hotel', verbose_name='Hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Issue',
                'verbose_name_plural': 'Room Issues',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['hotel', 'status', 'priority'], name='idx_issue_hotel_status_prio'), models.Index(fields=['room', 'status', 'blocking'], name='idx_issue_room_blocking')],
            },
        ),
    ]
